/**
 * YouTube channel — thin wrapper around existing fetchYoutubeSource.
 * Does NOT reimplement caption chain.
 */

import { extractYoutubeVideoId } from '@/lib/youtubeSourceId';
import { fetchYoutubeSource } from '@/lib/youtubeSource';
import { isYoutubeHost } from '../ssrf';
import type { SourceChannel, SourceFetchOpts, SourceIngestResult } from '../types';

function looksLikeYoutubeUrl(raw: string): boolean {
  const s = (raw || '').trim();
  if (!s) return false;
  if (/^[A-Za-z0-9_-]{11}$/.test(s)) return true;
  try {
    const withProto = /^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(s) ? s : `https://${s}`;
    const u = new URL(withProto);
    return isYoutubeHost(u.hostname);
  } catch {
    return /youtube\.com|youtu\.be/i.test(s);
  }
}

export const youtubeChannel: SourceChannel = {
  id: 'youtube',
  backends: ['youtubeSource-chain'],
  canHandle(url: string): boolean {
    return looksLikeYoutubeUrl(url);
  },
  async fetch(url: string, opts?: SourceFetchOpts): Promise<SourceIngestResult> {
    const videoId = extractYoutubeVideoId(url);
    if (!videoId) {
      return {
        ok: false,
        platform: 'youtube',
        url: String(url || '').trim(),
        errorCode: 'INVALID_URL',
        error:
          'Link YouTube chưa đúng — cần watch / youtu.be / shorts / live (không dán playlist hay trang kênh). Không scrape HTML trang YouTube bằng kênh web.',
      };
    }

    const result = await fetchYoutubeSource(url, {
      preferredLangs: opts?.preferredLangs,
    });

    const text = (result.transcript || '').trim();
    return {
      ok: result.ok,
      platform: 'youtube',
      url: result.url || `https://www.youtube.com/watch?v=${videoId}`,
      videoId: result.videoId || videoId,
      title: result.title,
      author: result.channel,
      description: result.description,
      text: text || undefined,
      wordCount: result.wordCount ?? (text ? text.split(/\s+/).filter(Boolean).length : undefined),
      source: result.source,
      chain: result.chain,
      language: result.language,
      isAutoGenerated: result.isAutoGenerated,
      rewriteBrief: result.rewriteBrief,
      error: result.error,
      errorCode: result.errorCode,
    };
  },
};
