/**
 * Fetch YouTube title / description / captions for rewrite-as-similar-script flows.
 * SERVER-ONLY (API routes): uses child_process / fs.
 * Client must import extractYoutubeVideoId from youtubeSourceId.ts only.
 *
 * Caption sources (cùng loại dữ liệu transcript — không dùng description thay phụ đề):
 * 1) python youtube-transcript-api
 * 2) timedtext / player caption tracks
 */

import { spawn } from 'child_process';
import fs from 'fs';
import path from 'path';
import { extractYoutubeVideoId } from './youtubeSourceId';

export { extractYoutubeVideoId } from './youtubeSourceId';

export type YoutubeSourceResult = {
  ok: boolean;
  videoId?: string;
  url?: string;
  title?: string;
  description?: string;
  channel?: string;
  language?: string;
  isAutoGenerated?: boolean;
  transcript?: string;
  wordCount?: number;
  source?: 'captions' | 'description_only' | 'python_captions';
  rewriteBrief?: string;
  error?: string;
};

const MAX_TRANSCRIPT_CHARS = 14_000;
const MAX_DESC_CHARS = 4_000;

function watchUrl(videoId: string): string {
  return `https://www.youtube.com/watch?v=${videoId}`;
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCharCode(parseInt(h, 16)));
}

function truncate(s: string, max: number): string {
  const t = s.trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max - 1).trimEnd()}…`;
}

function parsePlayerResponse(html: string): Record<string, unknown> | null {
  const markers = [
    /ytInitialPlayerResponse\s*=\s*(\{)/,
    /var\s+ytInitialPlayerResponse\s*=\s*(\{)/,
  ];
  for (const re of markers) {
    const m = html.match(re);
    if (!m || m.index == null) continue;
    const start = m.index + m[0].length - 1;
    const json = extractBalancedJson(html, start);
    if (json) {
      try {
        return JSON.parse(json) as Record<string, unknown>;
      } catch {
        /* try next */
      }
    }
  }
  return null;
}

/** Extract JSON object starting at `{` by brace balance (string-aware). */
function extractBalancedJson(src: string, startIdx: number): string | null {
  if (src[startIdx] !== '{') return null;
  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let i = startIdx; i < src.length; i++) {
    const c = src[i];
    if (inStr) {
      if (esc) {
        esc = false;
      } else if (c === '\\') {
        esc = true;
      } else if (c === '"') {
        inStr = false;
      }
      continue;
    }
    if (c === '"') {
      inStr = true;
      continue;
    }
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return src.slice(startIdx, i + 1);
    }
  }
  return null;
}

type CaptionTrack = {
  baseUrl: string;
  languageCode?: string;
  name?: string;
  kind?: string;
  vssId?: string;
};

function pickCaptionTrack(
  tracks: CaptionTrack[],
  preferredLangs: string[],
): CaptionTrack | null {
  if (!tracks.length) return null;
  const norm = preferredLangs.map((l) => l.toLowerCase().split('-')[0]);

  const score = (t: CaptionTrack): number => {
    const code = (t.languageCode || '').toLowerCase();
    const base = code.split('-')[0];
    let s = 0;
    const prefIdx = norm.indexOf(base);
    if (prefIdx >= 0) s += 100 - prefIdx * 10;
    // Prefer manual over ASR
    if (t.kind !== 'asr' && !String(t.vssId || '').includes('.a')) s += 20;
    if (base === 'vi') s += 5;
    if (base === 'en') s += 3;
    return s;
  };

  return [...tracks].sort((a, b) => score(b) - score(a))[0] || null;
}

function parseCaptionXml(xml: string): string {
  const parts: string[] = [];
  const re = /<text\b[^>]*>([\s\S]*?)<\/text>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    const raw = m[1]
      .replace(/<[^>]+>/g, ' ')
      .replace(/\n+/g, ' ')
      .trim();
    const text = decodeHtmlEntities(raw).replace(/\s+/g, ' ').trim();
    if (text) parts.push(text);
  }
  return parts.join(' ').replace(/\s+/g, ' ').trim();
}

function parseCaptionJson3(jsonText: string): string {
  try {
    const data = JSON.parse(jsonText) as {
      events?: Array<{ segs?: Array<{ utf8?: string }> }>;
    };
    const parts: string[] = [];
    for (const ev of data.events || []) {
      for (const seg of ev.segs || []) {
        const t = (seg.utf8 || '').replace(/\n/g, ' ').trim();
        if (t && t !== '\n') parts.push(t);
      }
    }
    return parts.join(' ').replace(/\s+/g, ' ').trim();
  } catch {
    return '';
  }
}

async function fetchText(url: string, init?: RequestInit): Promise<string> {
  const res = await fetch(url, {
    ...init,
    headers: {
      'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
      'Accept-Language': 'vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7',
      ...(init?.headers || {}),
    },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url.slice(0, 80)}`);
  return res.text();
}

async function fetchOembed(videoId: string): Promise<{ title?: string; author?: string }> {
  try {
    const u = `https://www.youtube.com/oembed?url=${encodeURIComponent(watchUrl(videoId))}&format=json`;
    const res = await fetch(u, {
      headers: { 'User-Agent': 'Mozilla/5.0' },
    });
    if (!res.ok) return {};
    const j = (await res.json()) as { title?: string; author_name?: string };
    return { title: j.title, author: j.author_name };
  } catch {
    return {};
  }
}

function resolveTranscriptScript(): string | null {
  const candidates = [
    path.join(process.cwd(), 'src', 'python_core', 'fetch_youtube_transcript.py'),
    path.join(process.cwd(), 'python_core', 'fetch_youtube_transcript.py'),
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  return null;
}

function pythonBins(): string[] {
  return process.platform === 'win32'
    ? ['python', 'py', 'python3']
    : ['python3', 'python'];
}

async function fetchTranscriptViaPython(
  videoId: string,
  preferredLangs: string[],
): Promise<{
  transcript: string;
  language?: string;
  isAutoGenerated?: boolean;
} | null> {
  const script = resolveTranscriptScript();
  if (!script) return null;
  const langs = preferredLangs.map((l) => l.split('-')[0]).join(',');

  for (const bin of pythonBins()) {
    try {
      const result = await new Promise<{
        transcript: string;
        language?: string;
        isAutoGenerated?: boolean;
      } | null>((resolve) => {
        let settled = false;
        const finish = (v: {
          transcript: string;
          language?: string;
          isAutoGenerated?: boolean;
        } | null) => {
          if (settled) return;
          settled = true;
          resolve(v);
        };

        let child;
        try {
          child = spawn(bin, [script, videoId, langs], {
            windowsHide: true,
            shell: false,
            env: {
              ...process.env,
              PYTHONIOENCODING: 'utf-8',
              PYTHONUTF8: '1',
            },
          });
        } catch {
          finish(null);
          return;
        }

        const chunks: Buffer[] = [];
        const timer = setTimeout(() => {
          try {
            child.kill();
          } catch {
            /* ignore */
          }
          finish(null);
        }, 60_000);

        child.stdout?.on('data', (d: Buffer | string) => {
          chunks.push(Buffer.isBuffer(d) ? d : Buffer.from(String(d)));
        });
        child.stderr?.on('data', () => {
          /* ignore stderr noise */
        });
        child.on('error', () => {
          clearTimeout(timer);
          finish(null);
        });
        child.on('close', () => {
          clearTimeout(timer);
          try {
            const out = Buffer.concat(chunks).toString('utf8');
            const line = out.trim().split(/\r?\n/).filter(Boolean).pop() || '';
            const j = JSON.parse(line) as {
              ok?: boolean;
              transcript?: string;
              language?: string;
              is_auto_generated?: boolean;
            };
            if (j.ok && j.transcript && j.transcript.trim().length > 10) {
              finish({
                transcript: j.transcript.trim(),
                language: j.language,
                isAutoGenerated: j.is_auto_generated,
              });
              return;
            }
          } catch {
            /* try next bin */
          }
          finish(null);
        });
      });
      if (result) return result;
    } catch {
      /* try next python binary */
    }
  }
  return null;
}

function buildRewriteBrief(parts: {
  url: string;
  title: string;
  channel: string;
  transcript: string;
  language?: string;
}): string {
  // Chỉ dùng bản chép lời (phụ đề) — không dùng mô tả video
  return [
    '[NGUỒN YOUTUBE — VIẾT LẠI KỊCH BẢN TƯƠNG TỰ]',
    'Nguồn: BẢN CHÉP LỜI / PHỤ ĐỀ video (không dùng description).',
    'Nhiệm vụ: Dựa trên nhịp, ý tưởng, cấu trúc và chủ đề từ chép lời, sáng tạo kịch bản GỐC MỚI (tên nhân vật, chi tiết, twist khác). CẤM copy nguyên văn; chỉ lấy cảm hứng / khung truyện.',
    `URL: ${parts.url}`,
    parts.title ? `Tiêu đề: ${parts.title}` : '',
    parts.channel ? `Kênh: ${parts.channel}` : '',
    parts.language ? `Ngôn ngữ phụ đề: ${parts.language}` : '',
    '',
    '---',
    'BẢN CHÉP LỜI (phụ đề nguồn):',
    parts.transcript,
    '---',
    'Yêu cầu outline: bóc cốt truyện lõi từ chép lời → dàn ý chương → nhân vật (khuyết điểm / động cơ — không ép khuyết tật mạt thế).',
  ]
    .filter((line) => line !== '')
    .join('\n');
}

export async function fetchYoutubeSource(
  urlOrId: string,
  opts?: { preferredLangs?: string[] },
): Promise<YoutubeSourceResult> {
  const videoId = extractYoutubeVideoId(urlOrId);
  if (!videoId) {
    return { ok: false, error: 'Link YouTube không hợp lệ (cần watch / youtu.be / shorts / video ID).' };
  }

  const url = watchUrl(videoId);
  const preferredLangs = opts?.preferredLangs?.length
    ? opts.preferredLangs
    : ['vi', 'en', 'en-US', 'en-GB'];

  try {
    const [html, oembed] = await Promise.all([
      fetchText(url, { headers: { Accept: 'text/html' } }),
      fetchOembed(videoId),
    ]);

    const player = parsePlayerResponse(html);
    const videoDetails = (player?.videoDetails || {}) as Record<string, unknown>;
    const title =
      (typeof videoDetails.title === 'string' && videoDetails.title) ||
      oembed.title ||
      '';
    const description =
      (typeof videoDetails.shortDescription === 'string' && videoDetails.shortDescription) ||
      '';
    const channel =
      (typeof videoDetails.author === 'string' && videoDetails.author) ||
      oembed.author ||
      '';

    const captionsRoot = player?.captions as Record<string, unknown> | undefined;
    const tracklist = captionsRoot?.playerCaptionsTracklistRenderer as
      | Record<string, unknown>
      | undefined;
    const rawTracks = (tracklist?.captionTracks || []) as Array<Record<string, unknown>>;
    const tracks: CaptionTrack[] = rawTracks
      .map((t) => ({
        baseUrl: String(t.baseUrl || ''),
        languageCode: t.languageCode ? String(t.languageCode) : undefined,
        name:
          t.name && typeof t.name === 'object' && 'simpleText' in (t.name as object)
            ? String((t.name as { simpleText?: string }).simpleText || '')
            : undefined,
        kind: t.kind ? String(t.kind) : undefined,
        vssId: t.vssId ? String(t.vssId) : undefined,
      }))
      .filter((t) => t.baseUrl);

    let transcript = '';
    let language: string | undefined;
    let isAutoGenerated = false;
    let source: YoutubeSourceResult['source'] = 'python_captions';

    // IRON B10: một đường transcript duy nhất (python youtube-transcript-api)
    const py = await fetchTranscriptViaPython(videoId, preferredLangs);
    if (py?.transcript && py.transcript.length >= 20) {
      transcript = py.transcript;
      language = py.language;
      isAutoGenerated = py.isAutoGenerated ?? false;
      source = 'python_captions';
    }

    const transcriptTrim = truncate(transcript, MAX_TRANSCRIPT_CHARS);
    if (!transcriptTrim || transcriptTrim.length < 20) {
      return {
        ok: false,
        videoId,
        url,
        title,
        channel,
        description: truncate(description, MAX_DESC_CHARS),
        error:
          'Không lấy được phụ đề qua youtube-transcript-api. Không fallback timedtext/mô tả. ' +
          'Bật captions trên video hoặc sửa python_core fetch transcript.',
      };
    }
    // tracks still parsed for diagnostics but not used as contingency
    void tracks;

    const rewriteBrief = buildRewriteBrief({
      url,
      title,
      channel,
      transcript: transcriptTrim,
      language,
    });

    return {
      ok: true,
      videoId,
      url,
      title,
      description: truncate(description, MAX_DESC_CHARS),
      channel,
      language,
      isAutoGenerated,
      transcript: transcriptTrim,
      wordCount: transcriptTrim.split(/\s+/).filter(Boolean).length,
      source,
      rewriteBrief,
    };
  } catch (e) {
    return {
      ok: false,
      videoId,
      url,
      error: e instanceof Error ? e.message : String(e),
    };
  }
}
