/**
 * Fetch YouTube title / description / captions for rewrite-as-similar-script flows.
 * SERVER-ONLY (API routes): uses child_process / fs.
 * Client must import extractYoutubeVideoId from youtubeSourceId.ts only.
 *
 * Caption sources (cùng loại dữ liệu transcript — không dùng description thay phụ đề):
 * 1) python youtube-transcript-api (resolvePythonExe + PATH)
 * 2) timedtext / player captionTracks (fallback sau khi Python fail)
 */

import { spawn } from 'child_process';
import fs from 'fs';
import path from 'path';
import { extractYoutubeVideoId } from './youtubeSourceId';
import { resolvePythonExe } from '@/app/api/self-heal/media/mediaHelpers';

export { extractYoutubeVideoId } from './youtubeSourceId';

/** Stable fail codes — UI / support can map without parsing free text. */
export type YoutubeTranscriptFailCode =
  | 'INVALID_URL'
  | 'SCRIPT_MISSING'
  | 'PYTHON_NOT_FOUND'
  | 'PACKAGE_MISSING'
  | 'TIMEOUT'
  | 'NO_TRANSCRIPT'
  | 'TRANSCRIPTS_DISABLED'
  | 'VIDEO_UNAVAILABLE'
  | 'AGE_RESTRICTED'
  | 'IP_BLOCKED'
  | 'RATE_LIMITED'
  | 'EMPTY_TRANSCRIPT'
  | 'FETCH_FAILED'
  | 'NETWORK';

export type YoutubeSourceResult = {
  ok: boolean;
  videoId?: string;
  url?: string;
  title?: string;
  description?: string;
  channel?: string;
  language?: string;
  isAutoGenerated?: boolean;
  transcript?: string;
  wordCount?: number;
  source?: 'captions' | 'description_only' | 'python_captions';
  rewriteBrief?: string;
  error?: string;
  /** Machine code for logging / support */
  errorCode?: YoutubeTranscriptFailCode;
};

const MAX_TRANSCRIPT_CHARS = 14_000;
const MAX_DESC_CHARS = 4_000;

function watchUrl(videoId: string): string {
  return `https://www.youtube.com/watch?v=${videoId}`;
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#x27;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCharCode(parseInt(h, 16)));
}

function truncate(s: string, max: number): string {
  const t = s.trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max - 1).trimEnd()}…`;
}

function parsePlayerResponse(html: string): Record<string, unknown> | null {
  const markers = [
    /ytInitialPlayerResponse\s*=\s*(\{)/,
    /var\s+ytInitialPlayerResponse\s*=\s*(\{)/,
  ];
  for (const re of markers) {
    const m = html.match(re);
    if (!m || m.index == null) continue;
    const start = m.index + m[0].length - 1;
    const json = extractBalancedJson(html, start);
    if (json) {
      try {
        return JSON.parse(json) as Record<string, unknown>;
      } catch {
        /* try next */
      }
    }
  }
  return null;
}

/** Extract JSON object starting at `{` by brace balance (string-aware). */
function extractBalancedJson(src: string, startIdx: number): string | null {
  if (src[startIdx] !== '{') return null;
  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let i = startIdx; i < src.length; i++) {
    const c = src[i];
    if (inStr) {
      if (esc) {
        esc = false;
      } else if (c === '\\') {
        esc = true;
      } else if (c === '"') {
        inStr = false;
      }
      continue;
    }
    if (c === '"') {
      inStr = true;
      continue;
    }
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) return src.slice(startIdx, i + 1);
    }
  }
  return null;
}

type CaptionTrack = {
  baseUrl: string;
  languageCode?: string;
  name?: string;
  kind?: string;
  vssId?: string;
};

function pickCaptionTrack(
  tracks: CaptionTrack[],
  preferredLangs: string[],
): CaptionTrack | null {
  if (!tracks.length) return null;
  const norm = preferredLangs.map((l) => l.toLowerCase().split('-')[0]);

  const score = (t: CaptionTrack): number => {
    const code = (t.languageCode || '').toLowerCase();
    const base = code.split('-')[0];
    let s = 0;
    const prefIdx = norm.indexOf(base);
    if (prefIdx >= 0) s += 100 - prefIdx * 10;
    // Prefer manual over ASR
    if (t.kind !== 'asr' && !String(t.vssId || '').includes('.a')) s += 20;
    if (base === 'vi') s += 5;
    if (base === 'en') s += 3;
    return s;
  };

  return [...tracks].sort((a, b) => score(b) - score(a))[0] || null;
}

function parseCaptionXml(xml: string): string {
  const parts: string[] = [];
  const re = /<text\b[^>]*>([\s\S]*?)<\/text>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    const raw = m[1]
      .replace(/<[^>]+>/g, ' ')
      .replace(/\n+/g, ' ')
      .trim();
    const text = decodeHtmlEntities(raw).replace(/\s+/g, ' ').trim();
    if (text) parts.push(text);
  }
  return parts.join(' ').replace(/\s+/g, ' ').trim();
}

function parseCaptionJson3(jsonText: string): string {
  try {
    const data = JSON.parse(jsonText) as {
      events?: Array<{ segs?: Array<{ utf8?: string }> }>;
    };
    const parts: string[] = [];
    for (const ev of data.events || []) {
      for (const seg of ev.segs || []) {
        const t = (seg.utf8 || '').replace(/\n/g, ' ').trim();
        if (t && t !== '\n') parts.push(t);
      }
    }
    return parts.join(' ').replace(/\s+/g, ' ').trim();
  } catch {
    return '';
  }
}

async function fetchText(url: string, init?: RequestInit): Promise<string> {
  const res = await fetch(url, {
    ...init,
    headers: {
      'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
      'Accept-Language': 'vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7',
      ...(init?.headers || {}),
    },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching ${url.slice(0, 80)}`);
  return res.text();
}

async function fetchOembed(videoId: string): Promise<{ title?: string; author?: string }> {
  try {
    const u = `https://www.youtube.com/oembed?url=${encodeURIComponent(watchUrl(videoId))}&format=json`;
    const res = await fetch(u, {
      headers: { 'User-Agent': 'Mozilla/5.0' },
    });
    if (!res.ok) return {};
    const j = (await res.json()) as { title?: string; author_name?: string };
    return { title: j.title, author: j.author_name };
  } catch {
    return {};
  }
}

function resolveTranscriptScript(): string | null {
  const resourcesPath =
    (process as NodeJS.Process & { resourcesPath?: string }).resourcesPath || '';
  const cwd = process.cwd();
  const candidates = [
    // Packaged Electron (extraResources)
    resourcesPath
      ? path.join(resourcesPath, 'app.asar.unpacked', 'src', 'python_core', 'fetch_youtube_transcript.py')
      : '',
    resourcesPath
      ? path.join(resourcesPath, 'src', 'python_core', 'fetch_youtube_transcript.py')
      : '',
    resourcesPath
      ? path.join(resourcesPath, 'python_core', 'fetch_youtube_transcript.py')
      : '',
    path.join(cwd, 'src', 'python_core', 'fetch_youtube_transcript.py'),
    path.join(cwd, 'python_core', 'fetch_youtube_transcript.py'),
  ].filter(Boolean);
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }
  return null;
}

/**
 * Python candidates for youtube-transcript-api.
 * Order: PATH `python`/`py` first (user often `pip install` here), then
 * resolvePythonExe (portable / SuperAudioTools — may lack youtube-transcript-api).
 * Ver 1.0.5 bug: only bare PATH names; then preferred Omni python without package
 * wasted first attempt. Timedtext still runs if all Python fail.
 */
function pythonBins(): string[] {
  const bins: string[] = [];
  if (process.platform === 'win32') {
    bins.push('python', 'py', 'python3');
  } else {
    bins.push('python3', 'python');
  }
  try {
    const preferred = resolvePythonExe();
    // Avoid pushing bare "python" twice; absolute paths always append
    if (preferred && preferred !== 'python' && preferred !== 'py' && preferred !== 'python3') {
      bins.push(preferred);
    }
  } catch {
    /* ignore */
  }
  return [...new Set(bins.map((b) => b.trim()).filter(Boolean))];
}

/**
 * Timedtext / player caption track — same content type as captions (NOT description).
 * Used only after Python path fails so white machines / missing pip package still work.
 */
async function fetchTranscriptViaTimedtext(
  tracks: CaptionTrack[],
  preferredLangs: string[],
): Promise<{
  ok: true;
  transcript: string;
  language?: string;
  isAutoGenerated?: boolean;
} | { ok: false; detail: string }> {
  if (!tracks.length) {
    return { ok: false, detail: 'Player không có captionTracks.' };
  }
  const track = pickCaptionTrack(tracks, preferredLangs);
  if (!track?.baseUrl) {
    return { ok: false, detail: 'Không chọn được caption track phù hợp.' };
  }
  try {
    // Prefer json3 then srv3/xml
    const base = track.baseUrl;
    const urls = [
      base.includes('fmt=') ? base : `${base}${base.includes('?') ? '&' : '?'}fmt=json3`,
      base,
    ];
    let lastDetail = '';
    for (const u of urls) {
      try {
        const res = await fetch(u, {
          headers: {
            'User-Agent':
              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
            Accept: 'application/json, text/xml, */*',
            Referer: 'https://www.youtube.com/',
            'Accept-Language': 'vi-VN,vi;q=0.9,en-US;q=0.8,en;q=0.7',
          },
        });
        const body = await res.text();
        if (res.status === 429 || /Sorry\.\.\.|too many requests|rate.?limit/i.test(body)) {
          return {
            ok: false,
            detail: `Timedtext HTTP ${res.status} (YouTube rate-limit / chặn IP).`,
          };
        }
        if (!res.ok) {
          lastDetail = `Timedtext HTTP ${res.status}`;
          continue;
        }
        let text = '';
        if (body.trimStart().startsWith('{') || body.includes('"events"')) {
          text = parseCaptionJson3(body);
        } else {
          text = parseCaptionXml(body);
        }
        if (text.length >= 20) {
          return {
            ok: true,
            transcript: text,
            language: track.languageCode,
            isAutoGenerated:
              track.kind === 'asr' || String(track.vssId || '').includes('.a'),
          };
        }
        lastDetail = `Track ${track.languageCode || '?'} quá ngắn (${text.length} ký tự).`;
      } catch (e) {
        lastDetail = e instanceof Error ? e.message : String(e);
      }
    }
    return { ok: false, detail: lastDetail || 'timedtext empty' };
  } catch (e) {
    return {
      ok: false,
      detail: e instanceof Error ? e.message : String(e),
    };
  }
}

type PythonTranscriptOk = {
  ok: true;
  transcript: string;
  language?: string;
  isAutoGenerated?: boolean;
};

type PythonTranscriptFail = {
  ok: false;
  code: YoutubeTranscriptFailCode;
  detail: string;
  triedBins: string[];
};

type PythonTranscriptResult = PythonTranscriptOk | PythonTranscriptFail;

function normalizePyCode(raw: string | undefined): YoutubeTranscriptFailCode | null {
  if (!raw) return null;
  const c = raw.trim().toUpperCase();
  const known: YoutubeTranscriptFailCode[] = [
    'INVALID_URL',
    'SCRIPT_MISSING',
    'PYTHON_NOT_FOUND',
    'PACKAGE_MISSING',
    'TIMEOUT',
    'NO_TRANSCRIPT',
    'TRANSCRIPTS_DISABLED',
    'VIDEO_UNAVAILABLE',
    'AGE_RESTRICTED',
    'IP_BLOCKED',
    'RATE_LIMITED',
    'EMPTY_TRANSCRIPT',
    'FETCH_FAILED',
    'NETWORK',
  ];
  return (known as string[]).includes(c) ? (c as YoutubeTranscriptFailCode) : null;
}

/**
 * User-facing error: WHAT · WHERE · HOW TO FIX (Vietnamese, end-user first).
 * Pure helper — unit-testable without network.
 * Technical paths stay under «Chi tiết kỹ thuật» only.
 */
export function buildYoutubeTranscriptUserError(ctx: {
  code: YoutubeTranscriptFailCode;
  videoId?: string;
  url?: string;
  title?: string;
  channel?: string;
  detail?: string;
  /** Caption tracks seen in player HTML (diagnostic). */
  playerCaptionTrackCount?: number;
}): string {
  // User-facing location (no python/file jargon in main block)
  const whereParts: string[] = [
    'Bước «Phân tích» / lấy phụ đề video YouTube (Setup)',
  ];
  if (ctx.title) whereParts.push(`Video: «${ctx.title}»`);
  if (ctx.channel) whereParts.push(`Kênh: ${ctx.channel}`);
  if (ctx.url) whereParts.push(`Link: ${ctx.url}`);
  else if (ctx.videoId) whereParts.push(`Mã video: ${ctx.videoId}`);
  if (typeof ctx.playerCaptionTrackCount === 'number') {
    whereParts.push(
      ctx.playerCaptionTrackCount > 0
        ? 'YouTube có vẻ có phụ đề nhưng app không tải được nội dung.'
        : 'Video này không lộ phụ đề (CC) cho app.',
    );
  }

  const commonAlt =
    '• Cách khác: gõ tay cốt truyện vào ô «3. Cốt truyện» rồi bấm «Sinh kịch bản» (không bắt buộc lấy phụ đề).';

  let reason: string;
  let fix: string[];

  switch (ctx.code) {
    case 'INVALID_URL':
      reason = 'Link YouTube chưa đúng — app không nhận ra video.';
      fix = [
        '• Dán link dạng: youtube.com/watch?v=… · youtu.be/… · shorts/…',
        '• Không dán playlist, trang kênh, hay kết quả tìm kiếm.',
        commonAlt,
      ];
      break;
    case 'SCRIPT_MISSING':
      reason = 'Bản cài app thiếu thành phần lấy phụ đề (cần cài lại / cập nhật app).';
      fix = [
        '• Cập nhật hoặc cài lại AI Novel bản đầy đủ.',
        '• Thử video khác có bật CC (phụ đề).',
        commonAlt,
      ];
      break;
    case 'PYTHON_NOT_FOUND':
      reason =
        'Máy chưa có Python (công cụ phụ) — và đường lấy phụ đề trực tiếp cũng không thành công.';
      fix = [
        '• Thử video public khác có bật phụ đề (CC) rõ trên YouTube.',
        '• Kiểm tra mạng, tắt VPN thử lại.',
        '• (Tuỳ chọn) Cài Python 3 + tick Add to PATH, rồi: pip install youtube-transcript-api',
        commonAlt,
      ];
      break;
    case 'PACKAGE_MISSING':
      reason =
        'Thiếu thư viện lấy phụ đề trên máy — app đã thử cách khác nhưng vẫn không lấy được chữ.';
      fix = [
        '• Chọn video có phụ đề (CC) public, thử lại «Phân tích».',
        '• (Tuỳ chọn) PowerShell: pip install youtube-transcript-api → khởi động lại app.',
        commonAlt,
      ];
      break;
    case 'TIMEOUT':
      reason = 'Chờ quá lâu khi lấy phụ đề (mạng chậm hoặc YouTube phản hồi chậm).';
      fix = [
        '• Kiểm tra internet; tắt VPN nếu đang bật.',
        '• Đợi vài phút rồi bấm «Phân tích» lại.',
        commonAlt,
      ];
      break;
    case 'TRANSCRIPTS_DISABLED':
      reason = 'Video này đã tắt phụ đề (captions).';
      fix = [
        '• Chọn video khác có nút CC / Phụ đề trên YouTube.',
        '• Nếu là video của bạn: YouTube Studio → Phụ đề → bật hoặc tải lên.',
        commonAlt,
      ];
      break;
    case 'NO_TRANSCRIPT':
      reason = 'Không tìm thấy phụ đề phù hợp (chưa có CC, hoặc ngôn ngữ app chưa đọc được).';
      fix = [
        '• Mở video trên YouTube → bật CC (tự động cũng được).',
        '• Ưu tiên video có phụ đề tiếng Việt hoặc English.',
        '• Tránh video chỉ nhạc / im lặng / mới đăng chưa có phụ đề.',
        commonAlt,
      ];
      break;
    case 'VIDEO_UNAVAILABLE':
      reason = 'Video không xem được (đã xóa, riêng tư, chặn vùng, hoặc link sai).';
      fix = [
        '• Mở cùng link trên trình duyệt máy này — nếu YouTube cũng chặn thì app không lấy được.',
        '• Dùng video công khai (public).',
        commonAlt,
      ];
      break;
    case 'AGE_RESTRICTED':
      reason = 'Video giới hạn độ tuổi — app không lấy phụ đề được khi chưa đăng nhập YouTube.';
      fix = [
        '• Chọn video không bị hạn chế độ tuổi.',
        commonAlt,
      ];
      break;
    case 'IP_BLOCKED':
      reason = 'YouTube tạm chặn máy/mạng này khi lấy phụ đề.';
      fix = [
        '• Đợi 15–30 phút, hoặc đổi Wi‑Fi / mạng di động.',
        '• Không bấm «Phân tích» liên tục nhiều lần.',
        commonAlt,
      ];
      break;
    case 'RATE_LIMITED':
      reason = 'Bạn (hoặc mạng) đang bấm lấy phụ đề quá nhanh — YouTube giới hạn tạm thời.';
      fix = [
        '• Đợi vài phút rồi thử lại.',
        '• Giảm số lần bấm «Phân tích» liên tiếp.',
        commonAlt,
      ];
      break;
    case 'EMPTY_TRANSCRIPT':
      reason = 'Phụ đề gần như trống — không đủ chữ để viết lại kịch bản.';
      fix = [
        '• Chọn video có lời thoại / kể chuyện rõ.',
        '• Tránh video nhạc không lời hoặc clip quá ngắn.',
        commonAlt,
      ];
      break;
    case 'NETWORK':
      reason = 'Mất kết nối hoặc không vào được YouTube.';
      fix = [
        '• Kiểm tra Wi‑Fi / 4G; thử mở youtube.com trên trình duyệt.',
        '• Tắt proxy/VPN lạ rồi thử lại.',
        commonAlt,
      ];
      break;
    case 'FETCH_FAILED':
    default:
      reason =
        typeof ctx.playerCaptionTrackCount === 'number' && ctx.playerCaptionTrackCount === 0
          ? 'Không lấy được phụ đề — video có vẻ chưa bật captions (app không dùng mô tả video thay phụ đề).'
          : 'Không lấy được nội dung phụ đề sau khi thử các cách có sẵn.';
      fix = [
        '• Bật CC trên video hoặc chọn video public đã có phụ đề.',
        '• Thử lại sau vài phút (mạng / YouTube có thể chặn tạm).',
        commonAlt,
      ];
      break;
  }

  const techBits = [
    ctx.detail?.trim(),
    ctx.videoId ? `videoId=${ctx.videoId}` : '',
    typeof ctx.playerCaptionTrackCount === 'number'
      ? `playerTracks=${ctx.playerCaptionTrackCount}`
      : '',
    `code=${ctx.code}`,
  ].filter(Boolean);
  const detailLine =
    techBits.length > 0
      ? `\n🔧 Chi tiết kỹ thuật (hỗ trợ / dev): ${techBits.join(' · ')}`
      : '';

  return [
    '❌ Không lấy được phụ đề YouTube',
    '',
    `🔎 Vì sao: ${reason}`,
    '',
    '📍 Ở đâu:',
    ...whereParts.map((l) => `  · ${l}`),
    '',
    '✅ Cách khắc phục:',
    ...fix,
    detailLine,
  ]
    .filter((l) => l !== undefined)
    .join('\n')
    .trim();
}

/** Short toast line: reason + first fix (không cắt giữa đống kỹ thuật). */
export function summarizeYoutubeErrorForToast(full: string, maxLen = 220): string {
  const text = (full || '').trim();
  if (!text) return 'Không lấy được phụ đề YouTube.';
  const why = text.match(/🔎 Vì sao:\s*(.+)/)?.[1]?.trim();
  const firstFix = text
    .split('\n')
    .map((l) => l.trim())
    .find((l) => l.startsWith('• '));
  const core = [why, firstFix].filter(Boolean).join(' ');
  const out = core || text.replace(/\s+/g, ' ');
  if (out.length <= maxLen) return out;
  return `${out.slice(0, Math.max(0, maxLen - 1))}…`;
}

async function fetchTranscriptViaPython(
  videoId: string,
  preferredLangs: string[],
): Promise<PythonTranscriptResult> {
  const script = resolveTranscriptScript();
  if (!script) {
    return {
      ok: false,
      code: 'SCRIPT_MISSING',
      detail: 'Không tìm thấy fetch_youtube_transcript.py trong project/app pack.',
      triedBins: [],
    };
  }
  const langs = preferredLangs.map((l) => l.split('-')[0]).join(',');
  const triedBins: string[] = [];
  let lastFail: PythonTranscriptFail | null = null;
  let anySpawned = false;

  for (const bin of pythonBins()) {
    triedBins.push(bin);
    try {
      const result = await new Promise<PythonTranscriptResult>((resolve) => {
        let settled = false;
        const finish = (v: PythonTranscriptResult) => {
          if (settled) return;
          settled = true;
          resolve(v);
        };

        let child;
        try {
          child = spawn(bin, [script, videoId, langs], {
            windowsHide: true,
            shell: false,
            env: {
              ...process.env,
              PYTHONIOENCODING: 'utf-8',
              PYTHONUTF8: '1',
            },
          });
          anySpawned = true;
        } catch (e) {
          finish({
            ok: false,
            code: 'PYTHON_NOT_FOUND',
            detail: e instanceof Error ? e.message : String(e),
            triedBins: [...triedBins],
          });
          return;
        }

        const chunks: Buffer[] = [];
        const errChunks: Buffer[] = [];
        const timer = setTimeout(() => {
          try {
            child.kill();
          } catch {
            /* ignore */
          }
          finish({
            ok: false,
            code: 'TIMEOUT',
            detail: `Timeout 60s với binary «${bin}».`,
            triedBins: [...triedBins],
          });
        }, 60_000);

        child.stdout?.on('data', (d: Buffer | string) => {
          chunks.push(Buffer.isBuffer(d) ? d : Buffer.from(String(d)));
        });
        child.stderr?.on('data', (d: Buffer | string) => {
          errChunks.push(Buffer.isBuffer(d) ? d : Buffer.from(String(d)));
        });
        child.on('error', (err) => {
          clearTimeout(timer);
          finish({
            ok: false,
            code: 'PYTHON_NOT_FOUND',
            detail: `${bin}: ${err.message}`,
            triedBins: [...triedBins],
          });
        });
        child.on('close', () => {
          clearTimeout(timer);
          try {
            const out = Buffer.concat(chunks).toString('utf8');
            const line = out.trim().split(/\r?\n/).filter(Boolean).pop() || '';
            if (!line) {
              const stderr = Buffer.concat(errChunks).toString('utf8').trim().slice(0, 200);
              finish({
                ok: false,
                code: 'FETCH_FAILED',
                detail: stderr
                  ? `Python «${bin}» không in JSON. stderr: ${stderr}`
                  : `Python «${bin}» không trả output.`,
                triedBins: [...triedBins],
              });
              return;
            }
            const j = JSON.parse(line) as {
              ok?: boolean;
              transcript?: string;
              language?: string;
              is_auto_generated?: boolean;
              error?: string;
              code?: string;
            };
            if (j.ok && j.transcript && j.transcript.trim().length > 10) {
              finish({
                ok: true,
                transcript: j.transcript.trim(),
                language: j.language,
                isAutoGenerated: j.is_auto_generated,
              });
              return;
            }
            const code =
              normalizePyCode(j.code) ||
              (String(j.error || '').includes('not installed')
                ? 'PACKAGE_MISSING'
                : 'FETCH_FAILED');
            finish({
              ok: false,
              code,
              detail: String(j.error || 'Transcript fetch failed').slice(0, 400),
              triedBins: [...triedBins],
            });
          } catch (e) {
            finish({
              ok: false,
              code: 'FETCH_FAILED',
              detail: e instanceof Error ? e.message : String(e),
              triedBins: [...triedBins],
            });
          }
        });
      });
      if (result.ok) return result;
      lastFail = result;
      // PACKAGE_MISSING / SCRIPT — no point trying other bins for same missing package sometimes still try
      if (result.code === 'PACKAGE_MISSING' || result.code === 'TIMEOUT') {
        // still try next bin in case another python has the package
      }
      if (
        result.code === 'NO_TRANSCRIPT' ||
        result.code === 'TRANSCRIPTS_DISABLED' ||
        result.code === 'VIDEO_UNAVAILABLE' ||
        result.code === 'AGE_RESTRICTED' ||
        result.code === 'EMPTY_TRANSCRIPT'
      ) {
        // video-side failure — other python bins won't help
        return result;
      }
    } catch (e) {
      lastFail = {
        ok: false,
        code: 'FETCH_FAILED',
        detail: e instanceof Error ? e.message : String(e),
        triedBins: [...triedBins],
      };
    }
  }

  if (!anySpawned) {
    return {
      ok: false,
      code: 'PYTHON_NOT_FOUND',
      detail: `Không spawn được Python. Đã thử: ${triedBins.join(', ') || '(trống)'}.`,
      triedBins,
    };
  }

  return (
    lastFail || {
      ok: false,
      code: 'FETCH_FAILED',
      detail: `Không lấy được transcript. Đã thử: ${triedBins.join(', ')}.`,
      triedBins,
    }
  );
}

function buildRewriteBrief(parts: {
  url: string;
  title: string;
  channel: string;
  transcript: string;
  language?: string;
}): string {
  // Chỉ dùng bản chép lời (phụ đề) — không dùng mô tả video
  return [
    '[NGUỒN YOUTUBE — VIẾT LẠI KỊCH BẢN TƯƠNG TỰ]',
    'Nguồn: BẢN CHÉP LỜI / PHỤ ĐỀ video (không dùng description).',
    'Nhiệm vụ: Dựa trên nhịp, ý tưởng, cấu trúc và chủ đề từ chép lời, sáng tạo kịch bản GỐC MỚI (tên nhân vật, chi tiết, twist khác). CẤM copy nguyên văn; chỉ lấy cảm hứng / khung truyện.',
    `URL: ${parts.url}`,
    parts.title ? `Tiêu đề: ${parts.title}` : '',
    parts.channel ? `Kênh: ${parts.channel}` : '',
    parts.language ? `Ngôn ngữ phụ đề: ${parts.language}` : '',
    '',
    '---',
    'BẢN CHÉP LỜI (phụ đề nguồn):',
    parts.transcript,
    '---',
    'Yêu cầu outline: bóc cốt truyện lõi từ chép lời → dàn ý chương → nhân vật (khuyết điểm / động cơ — không ép trope khuyết tật theo thể loại).',
  ]
    .filter((line) => line !== '')
    .join('\n');
}

export async function fetchYoutubeSource(
  urlOrId: string,
  opts?: { preferredLangs?: string[] },
): Promise<YoutubeSourceResult> {
  const videoId = extractYoutubeVideoId(urlOrId);
  if (!videoId) {
    return {
      ok: false,
      errorCode: 'INVALID_URL',
      error: buildYoutubeTranscriptUserError({
        code: 'INVALID_URL',
        detail: String(urlOrId || '').slice(0, 120),
      }),
    };
  }

  const url = watchUrl(videoId);
  const preferredLangs = opts?.preferredLangs?.length
    ? opts.preferredLangs
    : ['vi', 'en', 'en-US', 'en-GB'];

  try {
    let html = '';
    let oembed: { title?: string; author?: string } = {};
    try {
      [html, oembed] = await Promise.all([
        fetchText(url, { headers: { Accept: 'text/html' } }),
        fetchOembed(videoId),
      ]);
    } catch (netErr) {
      // Still try Python captions even if watch page fails
      oembed = await fetchOembed(videoId);
      console.warn(
        '[youtubeSource] watch page fetch failed:',
        netErr instanceof Error ? netErr.message : netErr,
      );
    }

    const player = html ? parsePlayerResponse(html) : null;
    const videoDetails = (player?.videoDetails || {}) as Record<string, unknown>;
    const title =
      (typeof videoDetails.title === 'string' && videoDetails.title) ||
      oembed.title ||
      '';
    const description =
      (typeof videoDetails.shortDescription === 'string' && videoDetails.shortDescription) ||
      '';
    const channel =
      (typeof videoDetails.author === 'string' && videoDetails.author) ||
      oembed.author ||
      '';

    const captionsRoot = player?.captions as Record<string, unknown> | undefined;
    const tracklist = captionsRoot?.playerCaptionsTracklistRenderer as
      | Record<string, unknown>
      | undefined;
    const rawTracks = (tracklist?.captionTracks || []) as Array<Record<string, unknown>>;
    const tracks: CaptionTrack[] = rawTracks
      .map((t) => ({
        baseUrl: String(t.baseUrl || ''),
        languageCode: t.languageCode ? String(t.languageCode) : undefined,
        name:
          t.name && typeof t.name === 'object' && 'simpleText' in (t.name as object)
            ? String((t.name as { simpleText?: string }).simpleText || '')
            : undefined,
        kind: t.kind ? String(t.kind) : undefined,
        vssId: t.vssId ? String(t.vssId) : undefined,
      }))
      .filter((t) => t.baseUrl);

    let transcript = '';
    let language: string | undefined;
    let isAutoGenerated = false;
    let source: YoutubeSourceResult['source'] = 'python_captions';
    let pyFail: PythonTranscriptFail | null = null;
    let timedtextDetail = '';

    // 1) Python youtube-transcript-api (preferred when runtime + package present)
    const py = await fetchTranscriptViaPython(videoId, preferredLangs);
    if (py.ok) {
      if (py.transcript.length >= 20) {
        transcript = py.transcript;
        language = py.language;
        isAutoGenerated = py.isAutoGenerated ?? false;
        source = 'python_captions';
      } else {
        pyFail = {
          ok: false,
          code: 'EMPTY_TRANSCRIPT',
          detail: `Transcript chỉ ${py.transcript.length} ký tự (cần ≥20).`,
          triedBins: [],
        };
      }
    } else {
      pyFail = py;
    }

    // 2) Timedtext / player caption tracks — same content type (captions), NOT description.
    // Fixes ver 1.0.5 white-machine: no system Python / missing youtube-transcript-api.
    if (transcript.length < 20 && tracks.length > 0) {
      const tt = await fetchTranscriptViaTimedtext(tracks, preferredLangs);
      if (tt.ok && tt.transcript.length >= 20) {
        transcript = tt.transcript;
        language = tt.language || language;
        isAutoGenerated = tt.isAutoGenerated ?? isAutoGenerated;
        source = 'captions';
      } else if (!tt.ok) {
        timedtextDetail = tt.detail;
      }
    }

    const transcriptTrim = truncate(transcript, MAX_TRANSCRIPT_CHARS);
    if (!transcriptTrim || transcriptTrim.length < 20) {
      // Prefer actionable classification
      let code: YoutubeTranscriptFailCode = pyFail?.code || 'FETCH_FAILED';
      if (/rate-limit|HTTP 429|chặn IP|IP has been blocked|too many requests/i.test(timedtextDetail)) {
        code = /block/i.test(timedtextDetail) ? 'IP_BLOCKED' : 'RATE_LIMITED';
      }
      if (
        (code === 'FETCH_FAILED' ||
          code === 'NO_TRANSCRIPT' ||
          code === 'PYTHON_NOT_FOUND' ||
          code === 'PACKAGE_MISSING') &&
        tracks.length === 0
      ) {
        code = 'NO_TRANSCRIPT';
      }
      // Tracks exist but py only failed for env reasons → still FETCH after timedtext fail
      if (
        tracks.length > 0 &&
        (code === 'PYTHON_NOT_FOUND' || code === 'PACKAGE_MISSING')
      ) {
        code = 'FETCH_FAILED';
      }
      const detailParts = [
        pyFail?.detail,
        pyFail?.triedBins?.length ? `Python tried: ${pyFail.triedBins.join(', ')}` : '',
        timedtextDetail ? `Timedtext: ${timedtextDetail}` : '',
      ].filter(Boolean);

      return {
        ok: false,
        videoId,
        url,
        title,
        channel,
        description: truncate(description, MAX_DESC_CHARS),
        errorCode: code,
        error: buildYoutubeTranscriptUserError({
          code,
          videoId,
          url,
          title,
          channel,
          detail: detailParts.join(' · '),
          playerCaptionTrackCount: tracks.length,
        }),
      };
    }

    const rewriteBrief = buildRewriteBrief({
      url,
      title,
      channel,
      transcript: transcriptTrim,
      language,
    });

    return {
      ok: true,
      videoId,
      url,
      title,
      description: truncate(description, MAX_DESC_CHARS),
      channel,
      language,
      isAutoGenerated,
      transcript: transcriptTrim,
      wordCount: transcriptTrim.split(/\s+/).filter(Boolean).length,
      source,
      rewriteBrief,
    };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    const code: YoutubeTranscriptFailCode =
      /HTTP|fetch|network|ECONN|ENOTFOUND|ETIMEDOUT/i.test(msg) ? 'NETWORK' : 'FETCH_FAILED';
    return {
      ok: false,
      videoId,
      url,
      errorCode: code,
      error: buildYoutubeTranscriptUserError({
        code,
        videoId,
        url,
        detail: msg,
      }),
    };
  }
}
