import { postGenerate, postJson, API } from './apiClient';
/**
 * Module thiết lập ban đầu & Dàn ý tác phẩm (Novel Setup & Outline Generator)
 */
import type { SetupData } from '@/store/useNovelStore';


export const CO_THE_KHUYET_TAT = [
  'rách gân tay trái khiến kiếm chiêu bị lệch 1 phân',
  'mù mắt phải do vết cào của dị chủng cấp cao',
  'liệt chân trái phải bước đi tập tễnh cùng nạng sắt',
  'mất khứu giác do hít phải bụi phóng xạ mạt thế',
  'phổi bị tổn thương nặng chỉ có thể nín thở tối đa 15 giây',
  'cụt 2 ngón tay phải khiến việc nạp đạn súng bị chậm 2 giây'
];

export const KHONG_GIAN_HOANG_PHE = [
  'trạm xăng bỏ hoang ngập trong sương độc axit',
  'tầng hầm trung tâm thương mại bị rêu đỏ ăn mòn',
  'nhà kho đông lạnh cũ chứa đầy kén trứng của biến dị thể',
  'nhà thờ đổ nát có bức tượng đổ sập chặn lối thoát',
  'toa tàu điện ngầm mắc kẹt giữa đường hầm ngập nước',
  'phòng thí nghiệm sinh học đổ nát đầy bình chứa rò rỉ'
];

export const VAT_PHAM_MAC_DINH = [
  'Con dao găm rỉ sét cán gỗ',
  'Bình lọc nước cầm tay còn 1 lần lọc',
  'Bản đồ khu tị nạn rách góc',
  'Hộp quẹt đá hết gas nhưng còn tia lửa',
  'Sợi dây xích sắt dài 2 mét'
];

export const getFriendlyErrorMessage = (err: unknown): string => {
  const msg = err instanceof Error ? err.message : String(err);
  if (msg.includes('429') || msg.includes('Quota') || msg.includes('quota') || msg.includes('limit')) {
    return `⚠️ Hạn mức API miễn phí (Quota Exceeded 429) của bạn đã tạm thời cạn kiệt.\n\n💡 Hướng dẫn khắc phục:\n1. Truy cập https://aistudio.google.com/app/apikey để tạo thêm API Key miễn phí.\n2. Nhấp vào "API Keys" ở góc trên bên phải để thêm nhiều Key xoay vòng quota. Hệ thống sẽ TỰ ĐỘNG XOAY VÒNG khi hết hạn ngạch.\n3. Hoặc chờ 5-15 phút để Google tự reset hạn ngạch.`;
  }
  return `❌ Lỗi hệ thống AI: ${msg}`;
};

export async function randomTemplateAction(params: {
apiKey: string;
  apiKeys: string[];
  chu_de: string;
  phong_cach: string;
}): Promise<string> {
  const { chu_de, phong_cach } = params;
  void params.apiKey;
  void params.apiKeys;
  const data = await postGenerate('GENERATE_IDEAS', { chu_de, phong_cach });
  return String(data.idea || 'Không nhận được ý tưởng.');
}

export type YoutubeSourcePayload = {
  success: boolean;
  ok?: boolean;
  videoId?: string;
  url?: string;
  title?: string;
  description?: string;
  channel?: string;
  language?: string;
  isAutoGenerated?: boolean;
  transcript?: string;
  wordCount?: number;
  source?: string;
  rewriteBrief?: string;
  error?: string;
};

/** Lấy tiêu đề / mô tả / phụ đề YouTube để seed mo_ta (viết lại kịch bản tương tự). */
export async function fetchYoutubeSourceAction(params: {
  url: string;
  preferredLangs?: string[];
}): Promise<YoutubeSourcePayload> {
  return postJson<YoutubeSourcePayload>(API.youtubeSource, {
    url: params.url,
    preferredLangs: params.preferredLangs,
  });
}

export async function analyzeYoutubePlotAction(params: {
  sourceText: string;
  title?: string;
  similarityTarget?: number;
}): Promise<string> {
  const data = await postGenerate('ANALYZE_YOUTUBE_PLOT', {
    source_text: params.sourceText,
    title: params.title || '',
    similarity_target: params.similarityTarget ?? 80,
  });
  const mo =
    (typeof data.mo_ta === 'string' && data.mo_ta) ||
    (typeof data.idea === 'string' && data.idea) ||
    '';
  if (!mo.trim()) {
    throw new Error('AI không trả về cốt truyện sau phân tích.');
  }
  return mo.trim();
}

/** Tóm gọn dàn ý / cốt truyện từ kịch bản hoặc truyện dán (Viết tiếp). */
export async function summarizeScriptOutlineAction(params: {
  textContent: string;
}): Promise<{
  mo_ta: string;
  dan_y_tom_gon: string;
  tieu_de_goi_y: string;
}> {
  const text = params.textContent.trim();
  if (text.length < 80) {
    throw new Error('Cần dán nội dung ≥80 ký tự để tóm gọn dàn ý.');
  }
  const data = await postGenerate('SUMMARIZE_SCRIPT_OUTLINE', {
    text_content: text.slice(0, 50000),
  });
  const mo_ta = String(data.mo_ta || '').trim();
  if (!mo_ta) {
    throw new Error('AI không trả về dàn ý tóm gọn.');
  }
  return {
    mo_ta,
    dan_y_tom_gon: String(data.dan_y_tom_gon || '').trim(),
    tieu_de_goi_y: String(data.tieu_de_goi_y || '').trim(),
  };
}

/** Kế thừa di sản — import foundation từ truyện cũ. */
export async function importFoundationAction(params: {
  textContent: string;
}): Promise<Record<string, unknown>> {
  const text = params.textContent.trim();
  if (!text) {
    throw new Error('Vui lòng dán nội dung truyện vào đây.');
  }
  const data = await postGenerate('IMPORT_FOUNDATION', {
    text_content: text.slice(0, 50000),
  });
  const foundation = data.foundation as Record<string, unknown> | undefined;
  if (!foundation || typeof foundation !== 'object') {
    throw new Error('AI trả về dữ liệu foundation rỗng.');
  }
  return foundation;
}

export async function generateOutlineAction(params: {
  apiKey: string;
  apiKeys: string[];
  setupData: SetupData;
  youtubeRewrite?: {
    enabled: boolean;
    similarityTarget?: number;
    sourceTitle?: string;
    /** Captions / kịch bản dán — đối chiếu % trùng; caller xóa sau khi sinh xong */
    captionCache?: string;
    /** youtube | script — nhãn prompt viết lại */
    sourceKind?: 'youtube' | 'script';
  };
}): Promise<unknown> {
  const { setupData, youtubeRewrite } = params;
  void params.apiKey;
  void params.apiKeys;

  // Repair legacy mojibake ngon_ngu before outline (older builds saved "Ti?ng Vi?t")
  const ngon = (setupData.ngon_ngu || '').trim();
  const rewriteOn = !!youtubeRewrite?.enabled;
  const sourceKind = youtubeRewrite?.sourceKind === 'script' ? 'script' : 'youtube';
  const sim = Math.max(
    10,
    Math.min(100, Math.round(youtubeRewrite?.similarityTarget ?? 80)),
  );

  // Normalize chapter counts — empty string from UI breaks the prompt
  const soChuongN = Number(setupData.so_chuong);
  const so_chuong =
    Number.isFinite(soChuongN) && soChuongN >= 1
      ? Math.min(500, Math.round(soChuongN))
      : 10;
  const soTuN = Number(setupData.so_tu_chuong);
  const so_tu_chuong =
    Number.isFinite(soTuN) && soTuN >= 500
      ? Math.min(10000, Math.round(soTuN))
      : 4250;

  // Cốt truyện đã phân tích (không nhét full transcript thô)
  let mo_ta = String(setupData.mo_ta || '').trim();
  const isRawYt =
    mo_ta.startsWith('[NGUỒN YOUTUBE') ||
    mo_ta.startsWith('[RAW YOUTUBE') ||
    mo_ta.includes('BẢN CHÉP LỜI (phụ đề nguồn):');
  if (isRawYt && mo_ta.length > 3500) {
    mo_ta =
      mo_ta.slice(0, 3500) +
      '\n\n[…đã cắt bớt chép lời thô — bấm Phân tích để lấy cốt truyện gọn…]';
  } else if (mo_ta.length > 8000) {
    mo_ta = mo_ta.slice(0, 8000) + '\n\n[…đã cắt bớt…]';
  }

  // Nguồn mẫu (captions / kịch bản dán) — excerpt để đối chiếu %
  const captionCache = String(youtubeRewrite?.captionCache || '').trim();
  const captions_excerpt = captionCache
    ? captionCache.slice(0, 4500)
    : '';

  const defaultChuDe =
    sourceKind === 'script' ? 'Viết lại kịch bản có sẵn' : 'Viết lại từ YouTube';

  const safeSetup = {
    ...setupData,
    mo_ta,
    so_chuong,
    so_tu_chuong,
    // Tránh đẩy URL vào chu_de khi mode viết lại
    chu_de: rewriteOn
      ? setupData.chu_de && !/^https?:\/\//i.test(setupData.chu_de)
        ? setupData.chu_de
        : defaultChuDe
      : setupData.chu_de,
    phong_cach: rewriteOn
      ? `Trùng ý tưởng mẫu ~${sim}%`
      : setupData.phong_cach,
    ngon_ngu:
      !ngon || /Ti\?ng Vi\?t/i.test(ngon) || ngon.includes('\uFFFD')
        ? 'Tiếng Việt'
        : ngon,
    youtube_rewrite: rewriteOn,
    similarity_target: sim,
    youtube_title: youtubeRewrite?.sourceTitle || '',
    youtube_captions_excerpt: captions_excerpt,
    rewrite_source_kind: rewriteOn ? sourceKind : '',
  };

  return postGenerate(
    'GENERATE_OUTLINE',
    safeSetup as unknown as Record<string, unknown>,
  );
}

