import { postGenerate, postJson, API } from './apiClient';
/**
 * Module thiết lập ban đầu & Dàn ý tác phẩm (Novel Setup & Outline Generator)
 */
import type { SetupData } from '@/store/useNovelStore';


/** Gợi ý khuyết điểm (điểm yếu) — không ép khuyết tật mạt thế */
export const CO_THE_KHUYET_TAT = [
  'kiêu ngạo che giấu nỗi sợ bị coi thường',
  'nói dối khi bị dồn vào chân tường',
  'nghiện kiểm soát mọi người xung quanh',
  'trì hoãn quyết định quan trọng đến phút chót',
  'ghen tị thầm với thành công của người thân',
  'hy sinh bản thân quá mức đến mức tự hủy',
];

/** Gợi ý không gian (trung tính / đa thể loại) */
export const KHONG_GIAN_HOANG_PHE = [
  'căn hộ tầng cao lúc nửa đêm đèn nhấp nháy',
  'hành lang trường cũ vang tiếng bước chân',
  'quán cà phê góc phố giờ tan tầm',
  'phòng họp kính của tập đoàn sau giờ làm',
  'sân ga vắng lúc sương sớm',
  'thư viện tầng hầm chỉ còn một bóng đèn',
];

/** Gợi ý đạo cụ / vật ký ức (trung tính) */
export const VAT_PHAM_MAC_DINH = [
  'Chiếc nhẫn khắc chữ mờ',
  'Cuốn sổ tay rách góc',
  'Chiếc chìa khóa cũ không rõ cửa',
  'Ảnh polaroid phai màu',
  'Dây chuyền mẻ một mắt xích',
];

export const getFriendlyErrorMessage = (err: unknown): string => {
  const msg = err instanceof Error ? err.message : String(err);
  if (msg.includes('429') || msg.includes('Quota') || msg.includes('quota') || msg.includes('limit')) {
    return `⚠️ Hạn mức API miễn phí (Quota Exceeded 429) của bạn đã tạm thời cạn kiệt.\n\n💡 Hướng dẫn khắc phục:\n1. Truy cập https://aistudio.google.com/app/apikey để tạo thêm API Key miễn phí.\n2. Nhấp vào "API Keys" ở góc trên bên phải để thêm nhiều Key xoay vòng quota. Hệ thống sẽ TỰ ĐỘNG XOAY VÒNG khi hết hạn ngạch.\n3. Hoặc chờ 5-15 phút để Google tự reset hạn ngạch.`;
  }
  return `❌ Lỗi hệ thống AI: ${msg}`;
};

export async function randomTemplateAction(params: {
apiKey: string;
  apiKeys: string[];
  chu_de: string;
  phong_cach: string;
}): Promise<string> {
  const { chu_de, phong_cach } = params;
  void params.apiKey;
  void params.apiKeys;
  const de = String(chu_de || '').trim();
  const pc = String(phong_cach || '').trim();
  if (!de || !pc) {
    throw new Error(
      'Chua chon Setup Chu de va Phong cach. App khong tu gan mat the khi sinh y tuong.',
    );
  }
  const data = await postGenerate('GENERATE_IDEAS', { chu_de: de, phong_cach: pc });
  const idea = String(data.idea || data.mo_ta || '').trim();
  if (!idea) {
    throw new Error('API sinh y tuong tra rong. Khong dung fill cuc bo.');
  }
  return idea;
}

export type YoutubeSourcePayload = {
  success: boolean;
  ok?: boolean;
  videoId?: string;
  url?: string;
  title?: string;
  description?: string;
  channel?: string;
  language?: string;
  isAutoGenerated?: boolean;
  transcript?: string;
  wordCount?: number;
  source?: string;
  rewriteBrief?: string;
  error?: string;
};

/** Lấy tiêu đề / mô tả / phụ đề YouTube để seed mo_ta (viết lại kịch bản tương tự). */
export async function fetchYoutubeSourceAction(params: {
  url: string;
  preferredLangs?: string[];
}): Promise<YoutubeSourcePayload> {
  return postJson<YoutubeSourcePayload>(API.youtubeSource, {
    url: params.url,
    preferredLangs: params.preferredLangs,
  });
}

export async function analyzeYoutubePlotAction(params: {
  sourceText: string;
  title?: string;
  similarityTarget?: number;
}): Promise<string> {
  const data = await postGenerate('ANALYZE_YOUTUBE_PLOT', {
    source_text: params.sourceText,
    title: params.title || '',
    similarity_target: params.similarityTarget ?? 80,
  });
  const mo =
    (typeof data.mo_ta === 'string' && data.mo_ta) ||
    (typeof data.idea === 'string' && data.idea) ||
    '';
  if (!mo.trim()) {
    throw new Error('AI không trả về cốt truyện sau phân tích.');
  }
  return mo.trim();
}

/** Tóm gọn dàn ý / cốt truyện từ kịch bản hoặc truyện dán (Viết tiếp). */
export async function summarizeScriptOutlineAction(params: {
  textContent: string;
}): Promise<{
  mo_ta: string;
  dan_y_tom_gon: string;
  tieu_de_goi_y: string;
}> {
  const text = params.textContent.trim();
  if (text.length < 80) {
    throw new Error('Cần dán nội dung ≥80 ký tự để tóm gọn dàn ý.');
  }
  const data = await postGenerate('SUMMARIZE_SCRIPT_OUTLINE', {
    text_content: text.slice(0, 50000),
  });
  const mo_ta = String(data.mo_ta || '').trim();
  if (!mo_ta) {
    throw new Error('AI không trả về dàn ý tóm gọn.');
  }
  return {
    mo_ta,
    dan_y_tom_gon: String(data.dan_y_tom_gon || '').trim(),
    tieu_de_goi_y: String(data.tieu_de_goi_y || '').trim(),
  };
}

/** Kế thừa di sản — import foundation từ truyện cũ. */
export async function importFoundationAction(params: {
  textContent: string;
}): Promise<Record<string, unknown>> {
  const text = params.textContent.trim();
  if (!text) {
    throw new Error('Vui lòng dán nội dung truyện vào đây.');
  }
  const { useNovelStore } = await import('@/store/useNovelStore');
  const store = useNovelStore.getState();
  const styleHint = String(
    store.visualDnaPrompt || store.mediaStylePreset || '',
  ).trim();
  const chu_de = String(store.setup?.chu_de || '').trim();
  const phong_cach = String(store.setup?.phong_cach || '').trim();
  const data = await postGenerate('IMPORT_FOUNDATION', {
    text_content: text.slice(0, 50000),
    styleHint: styleHint || undefined,
    style: styleHint || undefined,
    visualDnaPrompt: store.visualDnaPrompt || '',
    chu_de: chu_de || undefined,
    phong_cach: phong_cach || undefined,
    genre: [chu_de, phong_cach].filter(Boolean).join(' / ') || undefined,
  });
  const foundation = data.foundation as Record<string, unknown> | undefined;
  if (!foundation || typeof foundation !== 'object') {
    throw new Error('AI trả về dữ liệu foundation rỗng.');
  }
  return foundation;
}

export async function generateOutlineAction(params: {
  apiKey: string;
  apiKeys: string[];
  setupData: SetupData;
  youtubeRewrite?: {
    enabled: boolean;
    similarityTarget?: number;
    sourceTitle?: string;
    /** Captions / kịch bản dán — đối chiếu % trùng; caller xóa sau khi sinh xong */
    captionCache?: string;
    /** youtube | script — nhãn prompt viết lại */
    sourceKind?: 'youtube' | 'script';
  };
}): Promise<unknown> {
  const { setupData, youtubeRewrite } = params;
  void params.apiKey;
  void params.apiKeys;

  // Repair legacy mojibake ngon_ngu before outline (older builds saved "Ti?ng Vi?t")
  const ngon = (setupData.ngon_ngu || '').trim();
  const rewriteOn = !!youtubeRewrite?.enabled;
  const sourceKind = youtubeRewrite?.sourceKind === 'script' ? 'script' : 'youtube';
  const sim = Math.max(
    10,
    Math.min(100, Math.round(youtubeRewrite?.similarityTarget ?? 80)),
  );

  // Normalize chapter counts — empty string from UI breaks the prompt
  const soChuongN = Number(setupData.so_chuong);
  const so_chuong =
    Number.isFinite(soChuongN) && soChuongN >= 1
      ? Math.min(500, Math.round(soChuongN))
      : 10;
  const soTuN = Number(setupData.so_tu_chuong);
  const so_tu_chuong =
    Number.isFinite(soTuN) && soTuN >= 500
      ? Math.min(10000, Math.round(soTuN))
      : 4250;

  // Cốt truyện đã phân tích (không nhét full transcript thô)
  let mo_ta = String(setupData.mo_ta || '').trim();
  const isRawYt =
    mo_ta.startsWith('[NGUỒN YOUTUBE') ||
    mo_ta.startsWith('[RAW YOUTUBE') ||
    mo_ta.includes('BẢN CHÉP LỜI (phụ đề nguồn):');
  if (isRawYt && mo_ta.length > 3500) {
    mo_ta =
      mo_ta.slice(0, 3500) +
      '\n\n[…đã cắt bớt chép lời thô — bấm Phân tích để lấy cốt truyện gọn…]';
  } else if (mo_ta.length > 8000) {
    mo_ta = mo_ta.slice(0, 8000) + '\n\n[…đã cắt bớt…]';
  }

  // Nguồn mẫu (captions / kịch bản dán) — excerpt để đối chiếu %
  const captionCache = String(youtubeRewrite?.captionCache || '').trim();
  const captions_excerpt = captionCache
    ? captionCache.slice(0, 4500)
    : '';

  const defaultChuDe =
    sourceKind === 'script' ? 'Viết lại kịch bản có sẵn' : 'Viết lại từ YouTube';

  const safeSetup = {
    ...setupData,
    mo_ta,
    so_chuong,
    so_tu_chuong,
    // Tránh đẩy URL vào chu_de khi mode viết lại
    chu_de: rewriteOn
      ? setupData.chu_de && !/^https?:\/\//i.test(setupData.chu_de)
        ? setupData.chu_de
        : defaultChuDe
      : setupData.chu_de,
    phong_cach: rewriteOn
      ? `Trùng ý tưởng mẫu ~${sim}%`
      : setupData.phong_cach,
    ngon_ngu:
      !ngon || /Ti\?ng Vi\?t/i.test(ngon) || ngon.includes('\uFFFD')
        ? 'Tiếng Việt'
        : ngon,
    youtube_rewrite: rewriteOn,
    similarity_target: sim,
    youtube_title: youtubeRewrite?.sourceTitle || '',
    youtube_captions_excerpt: captions_excerpt,
    rewrite_source_kind: rewriteOn ? sourceKind : '',
  };

  return postGenerate(
    'GENERATE_OUTLINE',
    safeSetup as unknown as Record<string, unknown>,
  );
}

