import { postGenerate, postJson, API, buildClientApiHeaders } from './apiClient';
/**
 * Module thiết lập ban đầu & Dàn ý tác phẩm (Novel Setup & Outline Generator)
 */
import type { SetupData } from '@/store/useNovelStore';


/** Gợi ý khuyết điểm (điểm yếu) — không ép trope khuyết tật theo thể loại */
export const CO_THE_KHUYET_TAT = [
  'kiêu ngạo che giấu nỗi sợ bị coi thường',
  'nói dối khi bị dồn vào chân tường',
  'nghiện kiểm soát mọi người xung quanh',
  'trì hoãn quyết định quan trọng đến phút chót',
  'ghen tị thầm với thành công của người thân',
  'hy sinh bản thân quá mức đến mức tự hủy',
];

/** Gợi ý không gian (trung tính / đa thể loại) */
export const KHONG_GIAN_HOANG_PHE = [
  'căn hộ tầng cao lúc nửa đêm đèn nhấp nháy',
  'hành lang trường cũ vang tiếng bước chân',
  'quán cà phê góc phố giờ tan tầm',
  'phòng họp kính của tập đoàn sau giờ làm',
  'sân ga vắng lúc sương sớm',
  'thư viện tầng hầm chỉ còn một bóng đèn',
];

/** Gợi ý đạo cụ / vật ký ức (trung tính) */
export const VAT_PHAM_MAC_DINH = [
  'Chiếc nhẫn khắc chữ mờ',
  'Cuốn sổ tay rách góc',
  'Chiếc chìa khóa cũ không rõ cửa',
  'Ảnh polaroid phai màu',
  'Dây chuyền mẻ một mắt xích',
];

export const getFriendlyErrorMessage = (err: unknown): string => {
  const msg = err instanceof Error ? err.message : String(err);

  // YouTube / phụ đề TRƯỚC quota — tránh "rate limit" YouTube bị nhầm thành Gemini 429
  if (
    msg.includes('phụ đề YouTube') ||
    msg.includes('youtube-transcript-api') ||
    msg.includes('fetch_youtube_transcript') ||
    msg.includes('Cách khắc phục') ||
    msg.includes('BẢN CHÉP LỜI') ||
    (msg.includes('❌') && (msg.includes('📍') || msg.includes('✅') || msg.includes('🔎')))
  ) {
    return msg.startsWith('❌') || msg.startsWith('⚠️') ? msg : `❌ ${msg}`;
  }

  // Gemini / LLM quota only (không match mọi chữ "limit")
  const isLlmQuota =
    /\b429\b/.test(msg) ||
    /quota exceeded/i.test(msg) ||
    /resource.?exhausted/i.test(msg) ||
    (/quota/i.test(msg) && /gemini|aistudio|generativelanguage|api key/i.test(msg));
  if (isLlmQuota) {
    return `⚠️ Hạn mức API miễn phí (Quota Exceeded 429) của bạn đã tạm thời cạn kiệt.\n\n💡 Hướng dẫn khắc phục:\n1. Truy cập https://aistudio.google.com/app/apikey để tạo thêm API Key miễn phí.\n2. Nhấp vào "API Keys" ở góc trên bên phải để thêm nhiều Key xoay vòng quota. Hệ thống sẽ TỰ ĐỘNG XOAY VÒNG khi hết hạn ngạch.\n3. Hoặc chờ 5-15 phút để Google tự reset hạn ngạch.`;
  }
  return `❌ Lỗi hệ thống AI: ${msg}`;
};

/**
 * Toast ngắn: lấy «Vì sao» + bước khắc phục đầu (tránh cắt giữa message dài).
 * Client-safe — không import youtubeSource (server-only).
 */
export function summarizeSetupErrorForToast(full: string, maxLen = 220): string {
  const text = (full || '').trim();
  if (!text) return 'Đã xảy ra lỗi.';
  const why = text.match(/🔎 Vì sao:\s*(.+)/)?.[1]?.trim();
  const firstFix = text
    .split('\n')
    .map((l) => l.trim())
    .find((l) => l.startsWith('• '));
  const core = [why, firstFix].filter(Boolean).join(' ');
  const out = core || text.replace(/\s+/g, ' ');
  if (out.length <= maxLen) return out;
  return `${out.slice(0, Math.max(0, maxLen - 1)).trimEnd()}…`;
}

export async function randomTemplateAction(params: {
apiKey: string;
  apiKeys: string[];
  chu_de: string;
  phong_cach: string;
}): Promise<string> {
  const { chu_de, phong_cach } = params;
  void params.apiKey;
  void params.apiKeys;
  const de = String(chu_de || '').trim();
  const pc = String(phong_cach || '').trim();
  if (!de || !pc) {
    throw new Error(
      'Chua chon Setup Chu de va Phong cach. App khong tu gan the loai mac dinh khi sinh y tuong.',
    );
  }
  const data = await postGenerate('GENERATE_IDEAS', { chu_de: de, phong_cach: pc });
  const idea = String(data.idea || data.mo_ta || '').trim();
  if (!idea) {
    throw new Error('API sinh y tuong tra rong. Khong dung fill cuc bo.');
  }
  return idea;
}

export type YoutubeSourcePayload = {
  success: boolean;
  ok?: boolean;
  videoId?: string;
  url?: string;
  title?: string;
  description?: string;
  channel?: string;
  language?: string;
  isAutoGenerated?: boolean;
  transcript?: string;
  wordCount?: number;
  source?: string;
  /** server chain: meta > python > timedtext > ytdlp */
  chain?: string[];
  rewriteBrief?: string;
  error?: string;
  errorCode?: string;
};

/** Multi-source ingest payload (YouTube + web). */
export type SourceIngestPayload = YoutubeSourcePayload & {
  platform?: 'youtube' | 'web' | 'unsupported';
  /** Canonical body text (same as transcript for YT). */
  text?: string;
  author?: string;
  isMultiSource?: boolean;
  sourcesCount?: number;
};

/**
 * Multi-source: YouTube captions chain | web article extract.
 * 400/422 → structured fail + title/description for soft-seed (không throw).
 */
export async function fetchSourceIngestAction(params: {
  url: string;
  preferredLangs?: string[];
}): Promise<SourceIngestPayload> {
  const res = await fetch(API.sourceIngest, {
    method: 'POST',
    headers: buildClientApiHeaders(),
    body: JSON.stringify({
      url: params.url,
      preferredLangs: params.preferredLangs,
    }),
  });
  const data = (await res.json().catch(() => ({}))) as SourceIngestPayload & {
    error?: string;
  };

  const text = String(data.text || data.transcript || '').trim();
  const channel = String(data.channel || data.author || '').trim();

  if (res.ok) {
    return {
      ...data,
      success: data.success !== false,
      ok: data.ok !== false,
      transcript: text || data.transcript,
      text: text || data.text,
      channel,
      author: data.author || channel,
    };
  }

  if (res.status === 400 || res.status === 422) {
    return {
      success: false,
      ok: false,
      platform: data.platform || 'unsupported',
      error: String(data.error || `HTTP ${res.status}`),
      errorCode: data.errorCode,
      videoId: data.videoId,
      url: data.url || params.url,
      title: data.title || '',
      channel,
      author: data.author || channel,
      description: data.description || '',
      transcript: text,
      text,
      source: data.source,
      chain: data.chain,
    };
  }

  throw new Error(
    String(data.error || `HTTP ${res.status} source-ingest`).trim() ||
      'Không gọi được /api/source-ingest.',
  );
}

/**
 * Lấy tiêu đề / mô tả / phụ đề YouTube (legacy endpoint).
 * 422 (captions fail) → trả object success:false + title/description (không throw),
 * để client soft-seed cốt truyện khi YouTube chặn phụ đề.
 * Chỉ throw khi mạng/HTTP 5xx / body rỗng.
 */
export async function fetchYoutubeSourceAction(params: {
  url: string;
  preferredLangs?: string[];
}): Promise<YoutubeSourcePayload> {
  const res = await fetch(API.youtubeSource, {
    method: 'POST',
    headers: buildClientApiHeaders(),
    body: JSON.stringify({
      url: params.url,
      preferredLangs: params.preferredLangs,
    }),
  });
  const data = (await res.json().catch(() => ({}))) as YoutubeSourcePayload & {
    error?: string;
  };

  if (res.ok) {
    return {
      ...data,
      success: data.success !== false,
      ok: data.ok !== false,
    };
  }

  // Captions unavailable / rate-limit / bad URL — structured fail for soft-seed
  if (res.status === 400 || res.status === 422) {
    return {
      success: false,
      ok: false,
      error: String(data.error || `HTTP ${res.status}`),
      errorCode: data.errorCode,
      videoId: data.videoId,
      url: data.url || params.url,
      title: data.title || '',
      channel: data.channel || '',
      description: data.description || '',
      transcript: data.transcript || '',
    };
  }

  throw new Error(
    String(data.error || `HTTP ${res.status} youtube-source`).trim() ||
      'Không gọi được /api/youtube-source.',
  );
}

/** Ghép title+mô tả thành seed phân tích khi không lấy được phụ đề / body. */
export function buildYoutubeMetadataSeed(meta: {
  title?: string;
  description?: string;
  channel?: string;
  url?: string;
  /** youtube (default) | web */
  platform?: 'youtube' | 'web';
}): string {
  const title = String(meta.title || '').trim();
  const channel = String(meta.channel || '').trim();
  const description = String(meta.description || '').trim();
  const url = String(meta.url || '').trim();
  const isWeb = meta.platform === 'web';
  const parts = [
    isWeb
      ? '[NGUỒN WEB — METADATA, KHÔNG PHẢI THÂN BÀI]'
      : '[NGUỒN YOUTUBE — METADATA, KHÔNG PHẢI PHỤ ĐỀ]',
    isWeb
      ? 'Lưu ý: Không trích được thân bài. Chỉ có tiêu đề + mô tả — bóc cốt truyện gợi ý, không bịa nội dung.'
      : 'Lưu ý: Phụ đề (captions) không lấy được. Chỉ có tiêu đề + mô tả video — bóc cốt truyện gợi ý, không bịa phụ đề.',
    title ? `Tiêu đề: ${title}` : '',
    channel ? (isWeb ? `Nguồn/site: ${channel}` : `Kênh: ${channel}`) : '',
    url ? `URL: ${url}` : '',
    description
      ? `${isWeb ? 'Mô tả trang' : 'Mô tả video'}:\n${description.slice(0, 6000)}`
      : '',
  ].filter(Boolean);
  return parts.join('\n\n').trim();
}

export async function analyzeYoutubePlotAction(params: {
  sourceText: string;
  title?: string;
  similarityTarget?: number;
  /** captions (default) | metadata when YouTube chặn phụ đề */
  sourceKind?: 'captions' | 'metadata';
}): Promise<string> {
  const data = await postGenerate('ANALYZE_YOUTUBE_PLOT', {
    source_text: params.sourceText,
    title: params.title || '',
    similarity_target: params.similarityTarget ?? 80,
    source_kind: params.sourceKind || 'captions',
  });
  const mo =
    (typeof data.mo_ta === 'string' && data.mo_ta) ||
    (typeof data.idea === 'string' && data.idea) ||
    '';
  if (!mo.trim()) {
    throw new Error('AI không trả về cốt truyện sau phân tích.');
  }
  return mo.trim();
}

/** Tóm gọn dàn ý / cốt truyện từ kịch bản hoặc truyện dán (Viết tiếp). */
export async function summarizeScriptOutlineAction(params: {
  textContent: string;
}): Promise<{
  mo_ta: string;
  dan_y_tom_gon: string;
  tieu_de_goi_y: string;
}> {
  const text = params.textContent.trim();
  if (text.length < 80) {
    throw new Error('Cần dán nội dung ≥80 ký tự để tóm gọn dàn ý.');
  }
  const data = await postGenerate('SUMMARIZE_SCRIPT_OUTLINE', {
    text_content: text.slice(0, 50000),
  });
  const mo_ta = String(data.mo_ta || '').trim();
  if (!mo_ta) {
    throw new Error('AI không trả về dàn ý tóm gọn.');
  }
  return {
    mo_ta,
    dan_y_tom_gon: String(data.dan_y_tom_gon || '').trim(),
    tieu_de_goi_y: String(data.tieu_de_goi_y || '').trim(),
  };
}

/** Kế thừa di sản — import foundation từ truyện cũ. */
export async function importFoundationAction(params: {
  textContent: string;
}): Promise<Record<string, unknown>> {
  const text = params.textContent.trim();
  if (!text) {
    throw new Error('Vui lòng dán nội dung truyện vào đây.');
  }
  const { useNovelStore } = await import('@/store/useNovelStore');
  const store = useNovelStore.getState();
  const styleHint = String(
    store.visualDnaPrompt || store.mediaStylePreset || '',
  ).trim();
  const chu_de = String(store.setup?.chu_de || '').trim();
  const phong_cach = String(store.setup?.phong_cach || '').trim();
  const data = await postGenerate('IMPORT_FOUNDATION', {
    text_content: text.slice(0, 50000),
    styleHint: styleHint || undefined,
    style: styleHint || undefined,
    visualDnaPrompt: store.visualDnaPrompt || '',
    chu_de: chu_de || undefined,
    phong_cach: phong_cach || undefined,
    genre: [chu_de, phong_cach].filter(Boolean).join(' / ') || undefined,
  });
  const foundation = data.foundation as Record<string, unknown> | undefined;
  if (!foundation || typeof foundation !== 'object') {
    throw new Error('AI trả về dữ liệu foundation rỗng.');
  }
  return foundation;
}

export async function generateOutlineAction(params: {
  apiKey: string;
  apiKeys: string[];
  setupData: SetupData;
  youtubeRewrite?: {
    enabled: boolean;
    similarityTarget?: number;
    sourceTitle?: string;
    /** Captions / kịch bản dán — đối chiếu % trùng; caller xóa sau khi sinh xong */
    captionCache?: string;
    /** youtube | script — nhãn prompt viết lại */
    sourceKind?: 'youtube' | 'script';
  };
}): Promise<unknown> {
  const { setupData, youtubeRewrite } = params;
  void params.apiKey;
  void params.apiKeys;

  // Repair legacy mojibake ngon_ngu before outline (older builds saved "Ti?ng Vi?t")
  const ngon = (setupData.ngon_ngu || '').trim();
  const rewriteOn = !!youtubeRewrite?.enabled;
  const sourceKind = youtubeRewrite?.sourceKind === 'script' ? 'script' : 'youtube';
  const sim = Math.max(
    10,
    Math.min(100, Math.round(youtubeRewrite?.similarityTarget ?? 80)),
  );

  // Normalize chapter/word scale — Free/Trial aware (cấm ép 4250 khi Free 600)
  const { normalizeSetupScaleForTier, resolveMeteredTierFromFlags } =
    await import('@/lib/commercial/freeLimitsPolicy');
  const liveFlags = (await import('@/store/useNovelStore')).useNovelStore.getState();
  const tier = resolveMeteredTierFromFlags({
    is_pro: liveFlags.is_pro,
    is_trial: liveFlags.is_trial,
    is_vip: liveFlags.is_vip,
  });
  const scaled = normalizeSetupScaleForTier(
    setupData.so_chuong,
    setupData.so_tu_chuong,
    tier,
  );
  const so_chuong = scaled.so_chuong;
  const so_tu_chuong = scaled.so_tu_chuong;

  // Cốt truyện đã phân tích (không nhét full transcript thô)
  let mo_ta = String(setupData.mo_ta || '').trim();
  const isRawYt =
    mo_ta.startsWith('[NGUỒN YOUTUBE') ||
    mo_ta.startsWith('[RAW YOUTUBE') ||
    mo_ta.includes('BẢN CHÉP LỜI (phụ đề nguồn):');
  if (isRawYt && mo_ta.length > 3500) {
    mo_ta =
      mo_ta.slice(0, 3500) +
      '\n\n[…đã cắt bớt chép lời thô — bấm Phân tích để lấy cốt truyện gọn…]';
  } else if (mo_ta.length > 8000) {
    mo_ta = mo_ta.slice(0, 8000) + '\n\n[…đã cắt bớt…]';
  }

  // Nguồn mẫu (captions / kịch bản dán) — excerpt để đối chiếu %
  const captionCache = String(youtubeRewrite?.captionCache || '').trim();
  const captions_excerpt = captionCache
    ? captionCache.slice(0, 4500)
    : '';

  const defaultChuDe =
    sourceKind === 'script' ? 'Viết lại kịch bản có sẵn' : 'Viết lại từ YouTube';

  const safeSetup = {
    ...setupData,
    mo_ta,
    so_chuong,
    so_tu_chuong,
    // Tránh đẩy URL vào chu_de khi mode viết lại
    chu_de: rewriteOn
      ? setupData.chu_de && !/^https?:\/\//i.test(setupData.chu_de)
        ? setupData.chu_de
        : defaultChuDe
      : setupData.chu_de,
    phong_cach: rewriteOn
      ? `Trùng ý tưởng mẫu ~${sim}%`
      : setupData.phong_cach,
    ngon_ngu:
      !ngon || /Ti\?ng Vi\?t/i.test(ngon) || ngon.includes('\uFFFD')
        ? 'Tiếng Việt'
        : ngon,
    youtube_rewrite: rewriteOn,
    similarity_target: sim,
    youtube_title: youtubeRewrite?.sourceTitle || '',
    youtube_captions_excerpt: captions_excerpt,
    rewrite_source_kind: rewriteOn ? sourceKind : '',
  };

  const { useNovelStore } = await import('@/store/useNovelStore');
  const scriptMode = useNovelStore.getState().scriptMode || 'chuyen_sau';
  const result = await postGenerate('GENERATE_OUTLINE', {
    ...(safeSetup as unknown as Record<string, unknown>),
    scriptMode,
  });
  // P2: MiroFish only at outline/lore — silent hooks after outline (never block)
  try {
    const { silentEnrichArcHooks } = await import('./integrationsModule');
    const title =
      typeof (safeSetup as { ten_tac_pham?: string }).ten_tac_pham === 'string'
        ? String((safeSetup as { ten_tac_pham?: string }).ten_tac_pham)
        : 'truyện';
    void silentEnrichArcHooks({
      context: 'outline',
      hypothesis: `Outline vừa tạo cho "${title}" — gợi ý móc lorebook / arc.`,
    });
  } catch {
    /* ignore */
  }
  return result;
}

