/**
 * Multi-source content ingest for «viết lại tương tự».
 * Agent-Reach-inspired channel registry — product-native, no agent-reach package.
 */

export type SourcePlatform = 'youtube' | 'web' | 'unsupported';

export type SourceFetchOpts = {
  preferredLangs?: string[];
  /** Override timeout per channel (ms). */
  timeoutMs?: number;
};

/** Stable fail codes — UI / support can map without parsing free text. */
export type SourceIngestFailCode =
  | 'INVALID_URL'
  | 'UNSUPPORTED_URL'
  | 'SSRF_BLOCKED'
  | 'TIMEOUT'
  | 'NETWORK'
  | 'HTTP_ERROR'
  | 'EMPTY_CONTENT'
  | 'FETCH_FAILED'
  | 'BODY_TOO_LARGE'
  /** Passthrough from YouTube channel */
  | 'NO_TRANSCRIPT'
  | 'TRANSCRIPTS_DISABLED'
  | 'VIDEO_UNAVAILABLE'
  | 'AGE_RESTRICTED'
  | 'IP_BLOCKED'
  | 'RATE_LIMITED'
  | 'PYTHON_NOT_FOUND'
  | 'PACKAGE_MISSING'
  | 'SCRIPT_MISSING';

export type SourceIngestResult = {
  ok: boolean;
  platform: SourcePlatform;
  url: string;
  title?: string;
  /** Channel name (YT) or site hostname (web). */
  author?: string;
  description?: string;
  /** Body text for cache % overlap + plot analyze. */
  text?: string;
  wordCount?: number;
  /**
   * youtube: captions | ytdlp_captions | audio_whisper | …
   * web: web_readability | web_direct | web_meta | web_jina
   */
  source?: string;
  chain?: string[];
  error?: string;
  errorCode?: SourceIngestFailCode | string;
  videoId?: string;
  language?: string;
  isAutoGenerated?: boolean;
  rewriteBrief?: string;
  /** Multi-source Agent-Reach ingestion details */
  sources?: SourceIngestResult[];
  isMultiSource?: boolean;
  sourcesCount?: number;
};

export type SourceChannel = {
  id: SourcePlatform;
  backends: string[];
  canHandle(url: string): boolean;
  fetch(url: string, opts?: SourceFetchOpts): Promise<SourceIngestResult>;
};

export const MAX_SOURCE_TEXT_CHARS = 14_000;
export const MAX_WEB_HTML_BYTES = 2_000_000;
export const MAX_WEB_DESC_CHARS = 4_000;
